[build]
builder = "railpack"
buildCommand = "yarn turbo run build --filter=@clive/slack..."

[deploy]
startCommand = "yarn workspace @clive/slack start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
